global_settings:
  data_dir: ./data
  result_dir: ./results

extractor:
  backbone:
    ResNet:
      input: 256
      output: 2048
    EfficientNet:
      input: 256
      output: 1000
  dataset:
    blur_kernel: 7
    blur_sigma: 3
    batch_size: 64

reduction:
  t-SNE:
    n_components: 2
    n_iter: 5000
    init: pca
  UMAP:
    n_neighbors: 30
    min_dist: 0.01

clustering:
  K-Means:
    n_clusters: 6
  DBSCAN:
    eps: 2
    min_samples: 5
